services:
  - type: web
    name: spotfetch
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 5000
secretFiles:
  - mountPath: /etc/secrets/cookies.txt
